name: Deploy Flutter Web

on:
  push:
    branches:
      - prod/web

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH for github-fotocolab alias
        run: |
          mkdir -p ~/.ssh
          echo "Host github-fotocolab
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Add GitHub to known hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          flutter build web --release \
          --dart-define=BASE_URL=https://api.fotocolab.com/api/v1/fotocolab \
          --dart-define=HELP_EMAIL=fotocolabam@gmail.com \
          --dart-define=ENCRYPT_KEY=ThisIsMy32LengthKeyForEncryption \
          --dart-define=ENCRYPT_IV=1234567890 \
          --dart-define=IS_ENCRYPTION=true \
          --dart-define=ENABLE_DEBUG_PRINT=true \
          --dart-define=PRIVACY_POLICY=https://api.fotocolab.com/privacy \
          --dart-define=TERMS_AND_CONDITION=https://api.fotocolab.com/terms_and_conditions \
          --dart-define=REFUND_POLICY=https://api.fotocolab.com/refund_and_cancellation \
          --dart-define=CONTACT_US=https://api.fotocolab.com/contact \
          --dart-define=ENV=prod

      - name: Add custom domain
        run: |
          echo "admin.fotocolab.com" > build/web/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages