name: Deploy Flutter Web

on:
  push:
    branches:
      - prod/web

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          flutter build web --release \
          --dart-define=BASE_URL=https://api.fotocolab.com/api/v1/fotocolab \
          --dart-define=HELP_EMAIL=fotocolabam@gmail.com \
          --dart-define=ENCRYPT_KEY=ThisIsMy32LengthKeyForEncryption \
          --dart-define=ENCRYPT_IV=1234567890 \
          --dart-define=IS_ENCRYPTION=true \
          --dart-define=ENABLE_DEBUG_PRINT=true \
          --dart-define=PRIVACY_POLICY=https://api.fotocolab.com/privacy \
          --dart-define=TERMS_AND_CONDITION=https://api.fotocolab.com/terms-and-conditions \
          --dart-define=REFUND_POLICY=https://api.fotocolab.com/refund-and-cancellation \
          --dart-define=CONTACT_US=https://api.fotocolab.com/contact \
          --dart-define=ENV=prod

      - name: Preserve custom domain
        run: |
          echo "admin.fotocolab.com" > build/web/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages